version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: chatbot_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: chatbot_project_api2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6000:5432"

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  fastapi:
    build:
      context: ./fastapi
    container_name: fastapi
    environment:
      DATABASE_URL: postgresql://postgres:123@postgres:6000/chatbot_project_api2
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    depends_on:
      - postgres
      - minio
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  minio_data:
